packages:
  - "packages/*"
  - "examples/*"
  - "examples/passport/*"
  - "docs"

catalogs:
  prod:
    "@fastify/cookie": "11.0.2"
    "@fastify/multipart": "9.3.0"
    "@globalart/nestjs-zod": "1.0.0"
    "@globalart/oxide": "1.0.0"
    "@nestjs/common": "^11.1.9"
    "@nestjs/core": "^11.1.9"
    "@nestjs/microservices": "11.1.10"
    "@nestjs/platform-fastify": "11.1.10"
    "@nestjs/platform-socket.io": "11.1.9"
    "@nestjs/swagger": "^11.2.3"
    "@nestjs/testing": "^11.1.9"
    "@nestjs/throttler": "^6.4.0"
    "@nestjs/terminus": "11.0.0"
    "@nestjs/typeorm": "^11.0.0"
    "@socket.io/redis-adapter": "^8.3.0"
    "class-transformer": "^0.5.1"
    "class-validator": "^0.14.0"
    "date-fns": "4.1.0"
    "deepmerge": "^4.3.1"
    "dequal": "2.0.3"
    "etcd3": "1.1.2"
    "express": "^5.1.0"
    "fastify": "^5.6.2"
    "inflection": "3.0.2"
    "lodash": "^4.17.21"
    "mysql": "^2.18.1"
    "nanoid": "5.1.6"
    "node-fetch": "^3.3.2"
    "openid-connect": "^1.2.4"
    "passport": "^0.7.0"
    "prettier": "^3.6.2"
    "redis": "^5.10.0"
    "ts-pattern": "5.9.0"
    "url": "0.11.4"
    "uuid": "13.0.0"
    "zod": "4.2.1"
  dev:
    "@golevelup/ts-jest": "^1.1.1"
    "@nestjs/common": "^11.1.9"
    "@nestjs/core": "^11.1.9"
    "@nestjs/swagger": "^11.2.3"
    "@nestjs/testing": "^11.1.9"
    "@nestjs/typeorm": "^11.0.0"
    "@types/express": "^5.0.5"
    "@types/jest": "^30.0.0"
    "@types/lodash": "^4.17.21"
    "@types/merge-deep": "^3.0.0"
    "@types/node": "^25.0.0"
    "@types/passport": "^1.0.17"
    "@types/supertest": "^6.0.3"
    "@typescript-eslint/eslint-plugin": "^8.47.0"
    "@typescript-eslint/parser": "^8.47.0"
    "class-transformer": "^0.5.1"
    "class-validator": "^0.14.2"
    "coveralls": "^3.1.1"
    "esbuild": "^0.27.0"
    "eslint": "^9.39.1"
    "eslint-config-prettier": "^10.1.5"
    "eslint-kit": "^11.39.0"
    "eslint-plugin-prettier": "^5.5.4"
    "express": "^5.1.0"
    "fastify": "^5.6.2"
    "jest": "^30.2.0"
    "lodash": "^4.17.21"
    "pg": "^8.16.3"
    "prettier": "^3.6.2"
    "reflect-metadata": "^0.2.2"
    "release-it": "19.2.0"
    "rxjs": "^7.8.2"
    "sqlite3": "^5.1.7"
    "supertest": "^7.1.3"
    "ts-jest": "^29.4.5"
    "ts-node": "^10.9.2"
    "tsdown": "0.18.2"
    "typeorm": "^0.3.27"
    "typescript": "^5.9.3"
    "zod": "^4.0.5"