packages:
  - "packages/*"
  - "ecosystem-examples/examples/*"
  - "docs"
verifyDepsBeforeRun: false

overrides:
  css-select: "4.3.0"
allowBuilds:
  '@apollo/protobufjs': true
  '@confluentinc/kafka-javascript': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  core-js: true
  core-js-pure: true
  esbuild: true
  hiredis: true
  protobufjs: true
  sqlite3: true
  unrs-resolver: true
